# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import fl_pb2 as fl__pb2


class IvirseServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Join = channel.stream_stream(
                '/fl.proto.IvirseService/Join',
                request_serializer=fl__pb2.ClientMessage.SerializeToString,
                response_deserializer=fl__pb2.ServerMessage.FromString,
                )


class IvirseServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Join(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IvirseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Join': grpc.stream_stream_rpc_method_handler(
                    servicer.Join,
                    request_deserializer=fl__pb2.ClientMessage.FromString,
                    response_serializer=fl__pb2.ServerMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fl.proto.IvirseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IvirseService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Join(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/fl.proto.IvirseService/Join',
            fl__pb2.ClientMessage.SerializeToString,
            fl__pb2.ServerMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
