# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftransport.proto\x12\ttransport\"2\n\nParameters\x12\x0f\n\x07tensors\x18\x01 \x03(\x0c\x12\x13\n\x0btensor_type\x18\x02 \x01(\t\"K\n\rClientRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12)\n\nparameters\x18\x02 \x01(\x0b\x32\x15.transport.Parameters\"I\n\x0bServerReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12)\n\nparameters\x18\x02 \x01(\x0b\x32\x15.transport.Parameters2I\n\tTransport\x12<\n\x04Join\x12\x18.transport.ClientRequest\x1a\x16.transport.ServerReply(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transport_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_PARAMETERS']._serialized_start=30
  _globals['_PARAMETERS']._serialized_end=80
  _globals['_CLIENTREQUEST']._serialized_start=82
  _globals['_CLIENTREQUEST']._serialized_end=157
  _globals['_SERVERREPLY']._serialized_start=159
  _globals['_SERVERREPLY']._serialized_end=232
  _globals['_TRANSPORT']._serialized_start=234
  _globals['_TRANSPORT']._serialized_end=307
# @@protoc_insertion_point(module_scope)
