# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greet.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgreet.proto\x12\x05greet\"2\n\nParameters\x12\x0f\n\x07tensors\x18\x01 \x03(\x0c\x12\x13\n\x0btensor_type\x18\x02 \x01(\t\"5\n\x0cHelloRequest\x12%\n\nparameters\x18\x01 \x01(\x0b\x32\x11.greet.Parameters\"3\n\nHelloReply\x12%\n\nparameters\x18\x01 \x01(\x0b\x32\x11.greet.Parameters\"E\n\x0c\x44\x65layedReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12$\n\x07request\x18\x03 \x03(\x0b\x32\x13.greet.HelloRequest\"\x1a\n\x0bTestRequest\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x18\n\tTestReply\x12\x0b\n\x03msg\x18\x01 \x01(\t2\x81\x02\n\x07Greeter\x12\x34\n\x08SayHello\x12\x12.greet.TestRequest\x1a\x10.greet.TestReply(\x01\x30\x01\x12;\n\x0fParrotSaysHello\x12\x13.greet.HelloRequest\x1a\x11.greet.HelloReply0\x01\x12\x43\n\x15\x43hattyClientSaysHello\x12\x13.greet.HelloRequest\x1a\x13.greet.DelayedReply(\x01\x12>\n\x10InteractingHello\x12\x13.greet.HelloRequest\x1a\x11.greet.HelloReply(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greet_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_PARAMETERS']._serialized_start=22
  _globals['_PARAMETERS']._serialized_end=72
  _globals['_HELLOREQUEST']._serialized_start=74
  _globals['_HELLOREQUEST']._serialized_end=127
  _globals['_HELLOREPLY']._serialized_start=129
  _globals['_HELLOREPLY']._serialized_end=180
  _globals['_DELAYEDREPLY']._serialized_start=182
  _globals['_DELAYEDREPLY']._serialized_end=251
  _globals['_TESTREQUEST']._serialized_start=253
  _globals['_TESTREQUEST']._serialized_end=279
  _globals['_TESTREPLY']._serialized_start=281
  _globals['_TESTREPLY']._serialized_end=305
  _globals['_GREETER']._serialized_start=308
  _globals['_GREETER']._serialized_end=565
# @@protoc_insertion_point(module_scope)
