# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greet.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgreet.proto\x12\x05greet\"2\n\nParameters\x12\x0f\n\x07tensors\x18\x01 \x03(\x0c\x12\x13\n\x0btensor_type\x18\x02 \x01(\t\"G\n\rClientRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12%\n\nparameters\x18\x02 \x01(\x0b\x32\x11.greet.Parameters\"E\n\x0bServerReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12%\n\nparameters\x18\x02 \x01(\x0b\x32\x11.greet.Parameters2K\n\x07Greeter\x12@\n\x10InteractingHello\x12\x14.greet.ClientRequest\x1a\x12.greet.ServerReply(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greet_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_PARAMETERS']._serialized_start=22
  _globals['_PARAMETERS']._serialized_end=72
  _globals['_CLIENTREQUEST']._serialized_start=74
  _globals['_CLIENTREQUEST']._serialized_end=145
  _globals['_SERVERREPLY']._serialized_start=147
  _globals['_SERVERREPLY']._serialized_end=216
  _globals['_GREETER']._serialized_start=218
  _globals['_GREETER']._serialized_end=293
# @@protoc_insertion_point(module_scope)
